spring:
  datasource:
    url: jdbc:mysql://events-db:3308/events-api?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

application:
  title: Events API
  description: API to CRUD all information relative to events

jwt:
  secret-key: "c2VjcmV0c2hpdA=="