spring:
  datasource:
    url: jdbc:mysql://events-db:3308/events-api?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

application:
  title: Events API
  description: API to CRUD all information relative to events

jwt:
  secret-key: "yF_0Q4yG1y1I8QucdiufhLItC5i5yKNL9908p8Qym3zAWHxDyjpfIzBgfIwL06c7mQMW2WWkAPowAhAhN-QDIvwivvyT9fMy1KhLIRQd_EY8RSd3VWsHU1jJsrDaC5pjMoVGxcyvNMBl-WG4CIT40vX54NiwUls3pJhzrvCOmKk"