version: "3.8"

services:
  events-db:
    container_name: events-db
    image: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=events-api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    volumes:
      - events-db:/var/lib/mysql
  events-api:
    container_name: events-api
    depends_on:
      - events-db
    build: events-api/.
    restart: on-failure
    ports:
      - "8080:8080"

volumes:
    events-db:
