version: "3.8"
name: booking

services:
  events-db:
    container_name: events-db
    image: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=events-api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    volumes:
      - events-db:/var/lib/mysql
    networks:
      - booking
  events-api:
    container_name: events-api
    depends_on:
      - events-db
    build: events-api/.
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - booking

  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: 
      - on-failure
    networks:
      - booking
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=booking


  user-api:
    container_name: user-api
    build: userApi/.
    restart: on-failure
    ports:
      - "3001:3001"
    networks:
      - booking
    depends_on:
      - serviceName

  operator-api:
    container_name: operator-api
    build: operatorApi/.
    restart: on-failure
    ports:
      - "3002:3002"
    networks:
      - booking

  admin-api:
    container_name: admin-api
    build: adminApi/.
    restart: on-failure
    environment:
      - PORT=3003
      - TOKEN_Key = "yF_0Q4yG1y1I8QucdiufhLItC5i5yKNL9908p8Qym3zAWHxDyjpfIzBgfIwL06c7mQMW2WWkAPowAhAhN-QDIvwivvyT9fMy1KhLIRQd_EY8RSd3VWsHU1jJsrDaC5pjMoVGxcyvNMBl-WG4CIT40vX54NiwUls3pJhzrvCOmKk"
      - DB_Access =
    ports:
      - "3003:3003"
    networks:
      - booking

  test-client:
    container_name: test-client
    image: appropriate/curl
    hostname: test-client
    depends_on:
      - events-api
    command: ["sh", "-c", "sleep 20 && curl -s http://events-api:8080/api/events/book/1"]
    networks:
      - booking

volumes:
    events-db:
      name: events-db

networks:
  booking:
    name: booking