version: "3.8"
name: booking

services:
  events-db:
    container_name: events-db
    image: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=events-api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    volumes:
      - events-db:/var/lib/mysql
    networks:
      - booking
  events-api:
    container_name: events-api
    depends_on:
      - events-db
    build: events-api/.
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - booking

  user-api:
    container_name: user-api
    build: userApi/.
    restart: on-failure
    ports:
      - "3001:3001"
    networks:
      - booking
    secrets:
      - user-api-secret

  operator-api:
    container_name: operator-api
    build: operatorApi/.
    restart: on-failure
    ports:
      - "3002:3002"
    networks:
      - booking
    secrets:
      - operator-api-secret


  admin-api:
    container_name: admin-api
    build: adminApi/.
    restart: on-failure
    ports:
      - "3003:3003"
    networks:
      - booking
    secrets:
      - admin-api-secret

  mysql-service-ticket:
    container_name: mysql-service-ticket
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "service-ticket"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password_root"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql-ticket
    restart: always
    networks:
      - booking
  mysql-service-bank:
    container_name: mysql-service-bank
    image: mysql:5.7
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: "service-bank"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password_root"
      MYSQL_TCP_PORT: "3307"
    volumes:
      - ./init-bank.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql-bank
    restart: always
    networks:
      - booking
  api-tickets:
    hostname: api-tickets
    build: ./service-ticket/
    depends_on:
      - mysql-service-ticket
      - mysql-service-bank
    container_name: api-tickets
    ports:
      - "3505:3505"
    networks:
      - booking
    restart: always
  api-bank:
    hostname: api-bank
    build: ./service-bank/
    depends_on:
      - mysql-service-ticket
      - mysql-service-bank
    container_name: api-bank
    ports:
      - "3506:3506"
    networks:
      - booking
    restart: always

volumes:
  db:
  events-db:
    name: events-db

networks:
  booking:
    external: true
    name: booking



secrets:
  operator-api-secret:
    file: ./operatorApi/.env
  user-api-secret:
    file: ./userApi/.env
  admin-api-secret:
    file: ./adminApi/.env
