version: '3.1'
services:
  mysql-service-ticket:
    container_name: mysql-service-ticket
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "service-ticket"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password_root"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql-ticket
    restart: always
    networks:
      - network-bank
  mysql-service-bank:
    container_name: mysql-service-bank
    image: mysql:5.7
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: "service-bank"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password_root"
      MYSQL_TCP_PORT: "3307"
    volumes:
      - ./init-bank.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql-bank
    restart: always
    networks:
      - network-bank
  api-tickets:
    hostname: api-tickets
    build: ./service-ticket/
    depends_on:
      - nginx
      - mysql-service-ticket
      - mysql-service-bank
    container_name: api-tickets
    ports:
      - "3505:3505"
    networks:
      - network-bank
  api-bank:
    hostname: api-bank
    build: ./service-bank/
    depends_on:
      - nginx
      - mysql-service-ticket
      - mysql-service-bank
    container_name: api-bank
    ports:
      - "3506:3506"
    networks:
      - network-bank
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
        - network-bank
networks:
  network-bank:
volumes:
  db:


